title: Wlecome to GitHub!
author: Steffan153
email: mathmammoth@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ### My description

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
